name: Noe Valley Nursery School
description: Web Developer from Somewhere
markdown: kramdown
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - bower.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
gems:
  - jekyll-sitemap